'use server';

/**
 * @fileOverview Generates a blog post with an image from keywords.
 *
 * - generateBlogPost - Generates a blog post including title, content, and an image.
 * - GenerateBlogPostInput - Input schema for the generation.
 * - GenerateBlogPostOutput - Output schema for the generation.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateBlogPostInputSchema = z.object({
  keywords: z.string().describe('Keywords to base the blog post on.'),
});
export type GenerateBlogPostInput = z.infer<typeof GenerateBlogPostInputSchema>;

const BlogPostSchema = z.object({
  title: z.string().describe('The catchy and SEO-friendly title of the blog post.'),
  description: z.string().describe('A short, compelling meta description for the blog post.'),
  category: z.string().describe('A relevant category for the blog post (e.g., "Web Development", "Data Science").'),
  content: z.string().describe('The full content of the blog post, formatted in HTML. Include headings (h2, h3), paragraphs (p), lists (ul, ol, li), and code blocks (pre, code).'),
});

const GenerateBlogPostOutputSchema = z.object({
  blogPost: BlogPostSchema,
  imageDataUri: z.string().describe("A data URI of the generated image or a placeholder URL. Expected format: 'data:<mimetype>;base64,<encoded_data>' or 'https://...'."),
  imageGenerated: z.boolean().describe("Indicates if the image was successfully generated by AI."),
});
export type GenerateBlogPostOutput = z.infer<typeof GenerateBlogPostOutputSchema>;


const blogPostPrompt = ai.definePrompt({
  name: 'blogPostPrompt',
  input: { schema: GenerateBlogPostInputSchema },
  output: { schema: BlogPostSchema },
  prompt: `You are an expert content creator for a Vietnamese Python community blog.
  Generate a high-quality blog post in Vietnamese based on the following keywords: {{{keywords}}}.
  The post should be informative, engaging, and well-structured.
  The content should be in HTML format.
  The category should be one of the following: Hướng dẫn, Web Development, Data Science, Machine Learning, Tin tức.
  `,
});

export async function generateBlogPost(input: GenerateBlogPostInput): Promise<GenerateBlogPostOutput> {
  // Generate blog post content first
  const postResponse = await blogPostPrompt(input);
  const blogPost = postResponse.output;

  if (!blogPost) {
    throw new Error('Failed to generate blog post content.');
  }

  let imageDataUri: string;
  let imageGenerated = false;

  try {
    // Try to generate the image
    const imageResponse = await ai.generate({
      model: 'googleai/imagen-4.0-fast-generate-001',
      prompt: `A high-quality, relevant image for a blog post about: ${input.keywords}`,
    });

    if (imageResponse.media?.url) {
      imageDataUri = imageResponse.media.url;
      imageGenerated = true;
    } else {
      throw new Error('Image generation succeeded but no URL was returned.');
    }
  } catch (error) {
    console.warn("AI Image generation failed, falling back to placeholder:", error);
    // If image generation fails, use a placeholder
    imageDataUri = 'https://picsum.photos/1200/630';
    imageGenerated = false;
  }

  return { blogPost, imageDataUri, imageGenerated };
}
